import 'package:flutter/material.dart';
import 'package:latlong2/latlong.dart';

import 'models.dart';

/// Demo dataset lifted verbatim from the design spec. This is the seam where
/// Convex queries will plug in later — screens only ever see these shapes.
abstract final class DemoData {
  static const venues = <String, Venue>{
    'v1': Venue(
      id: 'v1',
      name: 'The Foghorn Club',
      area: 'Mission, SF',
      addr: '2455 Harrison St, San Francisco',
      point: LatLng(37.7524, -122.4180),
    ),
    'v2': Venue(
      id: 'v2',
      name: 'Nightcrawler Records',
      area: 'Temescal, Oakland',
      addr: '486 40th St, Oakland',
      point: LatLng(37.8180, -122.2690),
    ),
    'v3': Venue(
      id: 'v3',
      name: 'Casa Quake',
      area: 'Bernal Heights, SF',
      addr: '(address with RSVP)',
      point: LatLng(37.7399, -122.4166),
    ),
    'v4': Venue(
      id: 'v4',
      name: 'The Rusty Anchor',
      area: 'Dogpatch, SF',
      addr: '701 22nd St, San Francisco',
      point: LatLng(37.7583, -122.3880),
    ),
    'v5': Venue(
      id: 'v5',
      name: 'Peralta Hall',
      area: 'West Oakland',
      addr: '1801 Peralta St, Oakland',
      point: LatLng(37.8060, -122.2910),
    ),
    'v6': Venue(
      id: 'v6',
      name: 'Sunset Bunker',
      area: 'Outer Sunset, SF',
      addr: '3820 Noriega St, San Francisco',
      point: LatLng(37.7540, -122.5040),
    ),
  };

  static final _demoToday = () {
    final now = DateTime.now();
    return DateTime(now.year, now.month, now.day);
  }();

  static DateTime _demoStartsAt(int daysFromToday, int hour) => DateTime(
    _demoToday.year,
    _demoToday.month,
    _demoToday.day + daysFromToday,
    hour,
  );

  static String _demoDateShort(int daysFromToday, int hour) => Gig.dateShortFor(
    _demoStartsAt(daysFromToday, hour).millisecondsSinceEpoch,
  );

  static String _demoDateLine(int daysFromToday, int hour, String doorsTime) =>
      Gig.dateLineFor(
        _demoStartsAt(daysFromToday, hour).millisecondsSinceEpoch,
        doorsTime,
        now: _demoToday,
      );

  /// Dates stay relative to app startup so every demo session has useful
  /// Tonight, This Week, and later results for discovery filtering.
  static final gigs = <Gig>[
    Gig(
      id: 'g1',
      title: 'Basement Blowout',
      venueId: 'v3',
      price: 0,
      startsAt: _demoStartsAt(0, 21),
      dateShort: _demoDateShort(0, 21),
      dateLine: _demoDateLine(0, 21, '8PM / 9PM'),
      time: '8PM / 9PM',
      when: GigWhen.tonight,
      flyKey: 'paper',
      lineup: ['b3', 'b4', 'b6'],
      going: 43,
      genres: ['hardcore', 'noise'],
      desc:
          'Four bands, one basement, zero cover. Bring earplugs (the foam kind).',
      tix: Ticketing.rsvp,
      ageRequirement: AgeRequirement.eighteenPlus,
    ),
    Gig(
      id: 'g2',
      title: 'Riptide Release Show',
      venueId: 'v1',
      price: 10,
      startsAt: _demoStartsAt(2, 21),
      dateShort: _demoDateShort(2, 21),
      dateLine: _demoDateLine(2, 21, '8PM / 9PM'),
      time: '8PM / 9PM',
      when: GigWhen.week,
      flyKey: 'blue',
      lineup: ['b1', 'b2'],
      going: 87,
      genres: ['garage', 'surf'],
      desc:
          "Foghorn Diet plays 'Riptide' front to back, then whatever falls out.",
      tix: Ticketing.rsvp,
      createdByBand: 'b1',
      discoveryListingReady: true,
    ),
    Gig(
      id: 'g3',
      title: 'Noise Night Vol. 12',
      venueId: 'v2',
      price: 8,
      startsAt: _demoStartsAt(3, 21),
      dateShort: _demoDateShort(3, 21),
      dateLine: _demoDateLine(3, 21, '9PM / 9:30PM'),
      time: '9PM / 9:30PM',
      when: GigWhen.week,
      flyKey: 'black',
      lineup: ['b4', 'b6'],
      going: 29,
      genres: ['noise', 'shoegaze'],
      desc: 'In-store racket between the record bins. BYO earplugs, again.',
      tix: Ticketing.rsvp,
      ageRequirement: AgeRequirement.eighteenPlus,
    ),
    Gig(
      id: 'g4',
      title: 'Pigeon Court + Mission Creep',
      venueId: 'v4',
      price: 12,
      startsAt: _demoStartsAt(4, 21),
      dateShort: _demoDateShort(4, 21),
      dateLine: _demoDateLine(4, 21, '8PM / 8:45PM'),
      time: '8PM / 8:45PM',
      when: GigWhen.week,
      flyKey: 'bluetype',
      lineup: ['b2', 'b3'],
      going: 56,
      genres: ['post-punk', 'hardcore'],
      desc: 'Double bill. Loud then louder. Tickets through the venue.',
      tix: Ticketing.external,
      ageRequirement: AgeRequirement.twentyOnePlus,
      externalUrl: 'https://example.com/tickets/pigeon-court',
    ),
    Gig(
      id: 'g5',
      title: 'All-Ages Matinee',
      venueId: 'v5',
      price: 0,
      startsAt: _demoStartsAt(5, 14),
      dateShort: _demoDateShort(5, 14),
      dateLine: _demoDateLine(5, 14, '1:30PM / 2PM'),
      time: '1:30PM / 2PM',
      when: GigWhen.week,
      flyKey: 'yellow',
      lineup: ['b5', 'b6', 'b3'],
      going: 61,
      genres: ['punk'],
      desc: 'Daylight punk. Kids welcome, chaperones tolerated.',
      tix: Ticketing.rsvp,
      ageRequirement: AgeRequirement.allAges,
    ),
    Gig(
      id: 'g6',
      title: 'Trash Panda Riot',
      venueId: 'v6',
      price: 5,
      startsAt: _demoStartsAt(10, 22),
      dateShort: _demoDateShort(10, 22),
      dateLine: _demoDateLine(10, 22, '9PM / 10PM'),
      time: '9PM / 10PM',
      when: GigWhen.later,
      flyKey: 'black',
      lineup: ['b5'],
      going: 18,
      genres: ['thrash', 'punk'],
      desc: 'One band, ninety minutes, a bunker by the beach.',
      tix: Ticketing.rsvp,
    ),
    Gig(
      id: 'g7',
      title: 'Fog City Fest — Day Show',
      venueId: 'v1',
      price: 15,
      startsAt: _demoStartsAt(12, 12),
      dateShort: _demoDateShort(12, 12),
      dateLine: _demoDateLine(12, 12, '12PM / 12:30PM'),
      time: '12PM / 12:30PM',
      when: GigWhen.later,
      flyKey: 'blue',
      lineup: ['b1', 'b2', 'b4', 'b5'],
      going: 112,
      genres: ['punk', 'garage'],
      desc: 'Eight hours, four stages worth of bands on one stage.',
      tix: Ticketing.external,
      externalUrl: 'https://example.com/tickets/fog-city-fest',
    ),
  ];

  static const bands = <String, Band>{
    'b1': Band(
      id: 'b1',
      name: 'Foghorn Diet',
      genres: ['garage', 'surf punk'],
      area: 'Mission, SF',
      color: Color(0xFF7B8FFF),
      initials: 'FD',
      followers: 486,
      bio:
          'Reverb-soaked garage punk from a Mission garage that actually floods. '
          'Two guitars, no pedalboard budget, all heart.',
      profileComplete: true,
      upcoming: ['g2', 'g7'],
      past: [
        PastGig('Riptide warmup — Casa Quake', 'JUL 12'),
        PastGig('Nightcrawler in-store', 'JUN 27'),
        PastGig('Peralta Hall benefit', 'JUN 6'),
        PastGig('Bunker session', 'MAY 16'),
      ],
    ),
    'b2': Band(
      id: 'b2',
      name: 'Pigeon Court',
      genres: ['post-punk'],
      area: 'Temescal, Oakland',
      color: Color(0xFFB9C4FF),
      initials: 'PC',
      followers: 1214,
      bio:
          'Wiry post-punk for people who alphabetize their records and then fight about it.',
      profileComplete: true,
      upcoming: ['g2', 'g4', 'g7'],
      past: [
        PastGig('Court Is In Session tour', 'JUL'),
        PastGig('Noise Night Vol. 11', 'JUN 20'),
      ],
    ),
    'b3': Band(
      id: 'b3',
      name: 'Mission Creep',
      genres: ['hardcore'],
      area: 'Mission, SF',
      color: Color(0xFFE4DC4A),
      initials: 'MC',
      followers: 743,
      bio: 'Fast, short, gone. Sets under 20 minutes, guaranteed.',
      profileComplete: true,
      upcoming: ['g1', 'g4', 'g5'],
      past: [
        PastGig('Basement series #4', 'JUL 5'),
        PastGig('All-Ages Matinee', 'JUN 14'),
      ],
    ),
    'b4': Band(
      id: 'b4',
      name: 'Dial Tone Grief',
      genres: ['noise rock', 'shoegaze'],
      area: 'Bernal Heights, SF',
      color: Color(0xFF8FE6C4),
      initials: 'DT',
      followers: 312,
      bio:
          'Two amps facing each other, one long argument. You will feel it in your teeth.',
      profileComplete: true,
      upcoming: ['g1', 'g3', 'g7'],
      past: [PastGig('Noise Night Vol. 10', 'MAY 30')],
    ),
    'b5': Band(
      id: 'b5',
      name: 'Trash Panda Riot',
      genres: ['thrash', 'party punk'],
      area: 'West Oakland',
      color: Color(0xFFF0A26B),
      initials: 'TP',
      followers: 927,
      bio:
          'Party thrash with a raccoon on the kick drum. The raccoon is drawn on. Probably.',
      profileComplete: true,
      upcoming: ['g5', 'g6', 'g7'],
      past: [
        PastGig('Riot Fest (the small one)', 'JUL 4'),
        PastGig('Peralta Hall blowout', 'JUN 21'),
      ],
    ),
    'b6': Band(
      id: 'b6',
      name: 'Static Bloom',
      genres: ['shoegaze', 'punk'],
      area: 'Berkeley',
      color: Color(0xFFD9A6E8),
      initials: 'SB',
      followers: 158,
      bio:
          'Loud flowers. Berkeley basements and borrowed fuzz pedals since 2025.',
      profileComplete: true,
      upcoming: ['g1', 'g3', 'g5'],
      past: [PastGig('First show ever — house party', 'JUN 28')],
    ),
  };

  /// Band media for Foghorn Diet, including its clips and demo photos.
  static const b1Media = <BandMedia>[
    BandMedia(
      id: 'bm1',
      bandId: 'b1',
      kind: MediaKind.video,
      url: null,
      title: 'This is what we sound like — live at Foghorn Club',
      caption: null,
      sizeBytes: null,
      views: 12400,
      lengthSec: 161,
      pinned: true,
      order: 0,
      isHero: false,
    ),
    BandMedia(
      id: 'bm2',
      bandId: 'b1',
      kind: MediaKind.video,
      url: null,
      title: 'Riptide (practice take, one mic)',
      caption: null,
      sizeBytes: null,
      views: 3100,
      lengthSec: 185,
      pinned: false,
      order: 1,
      isHero: false,
    ),
    BandMedia(
      id: 'bm3',
      bandId: 'b1',
      kind: MediaKind.video,
      url: null,
      title: 'Undertow — basement set',
      caption: null,
      sizeBytes: null,
      views: 1800,
      lengthSec: 142,
      pinned: false,
      order: 2,
      isHero: false,
    ),
    BandMedia(
      id: 'bm4',
      bandId: 'b1',
      kind: MediaKind.video,
      url: null,
      title: 'New song, no name yet',
      caption: null,
      sizeBytes: null,
      views: 942,
      lengthSec: 107,
      pinned: false,
      order: 3,
      isHero: false,
    ),
    BandMedia(
      id: 'bm5',
      bandId: 'b1',
      kind: MediaKind.video,
      url: null,
      title: 'Soundcheck goes wrong (fun)',
      caption: null,
      sizeBytes: null,
      views: 5600,
      lengthSec: 58,
      pinned: false,
      order: 4,
      isHero: false,
    ),
    BandMedia(
      id: 'bm6',
      bandId: 'b1',
      kind: MediaKind.photo,
      url: null,
      title: 'Photo 1',
      caption: null,
      sizeBytes: null,
      views: null,
      lengthSec: null,
      pinned: false,
      order: 0,
      isHero: false,
    ),
    BandMedia(
      id: 'bm7',
      bandId: 'b1',
      kind: MediaKind.photo,
      url: null,
      title: 'Photo 2',
      caption: null,
      sizeBytes: null,
      views: null,
      lengthSec: null,
      pinned: false,
      order: 1,
      isHero: false,
    ),
  ];

  /// Generic band media shown for bands without their own uploaded clips.
  static const genericMedia = <BandMedia>[
    BandMedia(
      id: 'gm1',
      bandId: '_generic',
      kind: MediaKind.video,
      url: null,
      title: 'This is what we sound like',
      caption: null,
      sizeBytes: null,
      views: 1100,
      lengthSec: 130,
      pinned: true,
      order: 0,
      isHero: false,
    ),
    BandMedia(
      id: 'gm2',
      bandId: '_generic',
      kind: MediaKind.video,
      url: null,
      title: 'Live clip — last month',
      caption: null,
      sizeBytes: null,
      views: 640,
      lengthSec: 112,
      pinned: false,
      order: 1,
      isHero: false,
    ),
    BandMedia(
      id: 'gm3',
      bandId: '_generic',
      kind: MediaKind.video,
      url: null,
      title: 'Practice space take',
      caption: null,
      sizeBytes: null,
      views: 402,
      lengthSec: 153,
      pinned: false,
      order: 2,
      isHero: false,
    ),
    BandMedia(
      id: 'gm4',
      bandId: '_generic',
      kind: MediaKind.video,
      url: null,
      title: 'New one (rough)',
      caption: null,
      sizeBytes: null,
      views: 188,
      lengthSec: 79,
      pinned: false,
      order: 3,
      isHero: false,
    ),
    BandMedia(
      id: 'gm5',
      bandId: '_generic',
      kind: MediaKind.video,
      url: null,
      title: 'Full set audio',
      caption: null,
      sizeBytes: null,
      views: 871,
      lengthSec: 1324,
      pinned: false,
      order: 4,
      isHero: false,
    ),
  ];

  static const fanHistory = <PastGig>[
    PastGig('Basement series #4 — Casa Quake', 'JUL 5'),
    PastGig('Noise Night Vol. 11 — Nightcrawler', 'JUN 20'),
    PastGig('All-Ages Matinee — Peralta Hall', 'JUN 14'),
    PastGig('Peralta Hall benefit', 'JUN 6'),
  ];
}
